# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ac5ad78b09a72e45f1356519691032317a0943a6d7f5f0a7506e39e1d5ca9dff4aea2ffb089c4a7634214a1fd74fd541f3d9ac757ab23fac3ee4d549d71960c

test:
  secret_key_base: d5522297acf00ac433298215b73e951e0862f4dbcecc4b89566a186d8417d2814739b4e753b7a048c43bedf04ead781a51c4cd9bde2e54190d343f8715e39c34

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
